### ISSUE TITLE
Error when using sortType = random on randomImageFromSub

### ISSUE THREAD

**Issue by OwendB1** [Lanred-Dev/justreddit#1]
When trying to execute this I get the following error:
```
TypeError [Error]: Cannot read properties of undefined (reading 'children')
    at randomPostFromSub (C:\Users\owen\Documents\GitHub\thp-services\Bot\node_modules\justreddit\build\functions\randomPostFromSub.js:20:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async randomImageFromSub (C:\Users\owen\Documents\GitHub\thp-services\Bot\node_modules\justreddit\build\functions\randomImageFromSub.js:13:28)
```

**Comment by Lanred-Dev** [comment]
Working on a fix.

**Comment by Lanred-Dev** [comment]
Fixed.
